In [1]:
from pathlib import Path

project_root = Path("..")

usa_folder = project_root / "data" / "usa"

print("USA folder exists:", usa_folder.exists())

print(list(usa_folder.iterdir()))

USA folder exists: True
[WindowsPath('../data/usa/assumptions'), WindowsPath('../data/usa/budget_impact'), WindowsPath('../data/usa/clinical'), WindowsPath('../data/usa/costs'), WindowsPath('../data/usa/epidemiology'), WindowsPath('../data/usa/population'), WindowsPath('../data/usa/README.md'), WindowsPath('../data/usa/sensitivity')]

In [3]:
from pathlib import Path
import pandas as pd
import numpy as np

In [4]:
project_root = Path("..")

usa_data = project_root / "data" / "usa"
usa_reports = project_root / "reports" / "usa"

print("USA data folder:", usa_data.exists())
print("USA reports folder:", usa_reports.exists())

USA data folder: True
USA reports folder: True

In [6]:
from pathlib import Path
import pandas as pd

project_root = Path("..")

population_file = project_root / "data" / "usa" / "population" / "us_population.xlsx"

print(population_file.exists())

True

In [11]:
from pathlib import Path

population_file = project_root / "data" / "usa" / "population" / "us_population.csv"

print(population_file)
print("File size:", population_file.stat().st_size, "bytes")

..\data\usa\population\us_population.csv
File size: 53555 bytes

In [12]:
usa_population = pd.read_csv(population_file)

usa_population.head()

,SUMLEV,REGION,DIVISION,STATE,NAME,ESTIMATESBASE2020,POPESTIMATE2020,POPESTIMATE2021,POPESTIMATE2022,POPESTIMATE2023,...,RDOMESTICMIG2021,RDOMESTICMIG2022,RDOMESTICMIG2023,RDOMESTICMIG2024,RDOMESTICMIG2025,RNETMIG2021,RNETMIG2022,RNETMIG2023,RNETMIG2024,RNETMIG2025
0,10,0,0,0,United States,331516113,331578104,332100166,333996304,336755052,...,0.000000,0.000000,0.000000,0.000000,0.000000,1.133157,5.020630,6.751047,8.081071,3.702620
1,20,1,0,0,Northeast Region,57617560,57436027,57234503,57174375,57458539,...,-5.035383,-7.452027,-4.783077,-3.107894,-3.544532,-3.632267,-1.425326,4.125517,7.384999,0.704071
2,30,1,1,0,New England,15122087,15047713,15116021,15178293,15267275,...,2.864433,-2.549587,-1.971584,-0.870354,-1.791240,4.636760,4.712898,6.032734,7.954870,2.800945
3,30,1,2,0,Middle Atlantic,42495473,42388314,42118482,41996082,42191264,...,-7.855132,-9.217667,-5.799826,-3.917263,-4.179011,-6.583802,-3.636041,3.435790,7.178864,-0.054742
4,20,2,0,0,Midwest Region,68999462,68979566,68867096,68872112,69132050,...,-2.545350,-2.623233,-1.327003,-0.630161,0.230326,-1.743053,0.551433,3.237294,4.892725,2.817342

In [13]:
usa_population.columns

Index(['SUMLEV', 'REGION', 'DIVISION', 'STATE', 'NAME', 'ESTIMATESBASE2020',
       'POPESTIMATE2020', 'POPESTIMATE2021', 'POPESTIMATE2022',
       'POPESTIMATE2023', 'POPESTIMATE2024', 'POPESTIMATE2025', 'NPOPCHG_2020',
       'NPOPCHG_2021', 'NPOPCHG_2022', 'NPOPCHG_2023', 'NPOPCHG_2024',
       'NPOPCHG_2025', 'BIRTHS2020', 'BIRTHS2021', 'BIRTHS2022', 'BIRTHS2023',
       'BIRTHS2024', 'BIRTHS2025', 'DEATHS2020', 'DEATHS2021', 'DEATHS2022',
       'DEATHS2023', 'DEATHS2024', 'DEATHS2025', 'NATURALCHG2020',
       'NATURALCHG2021', 'NATURALCHG2022', 'NATURALCHG2023', 'NATURALCHG2024',
       'NATURALCHG2025', 'INTERNATIONALMIG2020', 'INTERNATIONALMIG2021',
       'INTERNATIONALMIG2022', 'INTERNATIONALMIG2023', 'INTERNATIONALMIG2024',
       'INTERNATIONALMIG2025', 'DOMESTICMIG2020', 'DOMESTICMIG2021',
       'DOMESTICMIG2022', 'DOMESTICMIG2023', 'DOMESTICMIG2024',
       'DOMESTICMIG2025', 'NETMIG2020', 'NETMIG2021', 'NETMIG2022',
       'NETMIG2023', 'NETMIG2024', 'NETMIG2025', 'RESIDUAL2020',
       'RESIDUAL2021', 'RESIDUAL2022', 'RESIDUAL2023', 'RESIDUAL2024',
       'RESIDUAL2025', 'GQESTIMATESBASE2020', 'GQESTIMATES2020',
       'GQESTIMATES2021', 'GQESTIMATES2022', 'GQESTIMATES2023',
       'GQESTIMATES2024', 'GQESTIMATES2025', 'RBIRTH2021', 'RBIRTH2022',
       'RBIRTH2023', 'RBIRTH2024', 'RBIRTH2025', 'RDEATH2021', 'RDEATH2022',
       'RDEATH2023', 'RDEATH2024', 'RDEATH2025', 'RNATURALCHG2021',
       'RNATURALCHG2022', 'RNATURALCHG2023', 'RNATURALCHG2024',
       'RNATURALCHG2025', 'RINTERNATIONALMIG2021', 'RINTERNATIONALMIG2022',
       'RINTERNATIONALMIG2023', 'RINTERNATIONALMIG2024',
       'RINTERNATIONALMIG2025', 'RDOMESTICMIG2021', 'RDOMESTICMIG2022',
       'RDOMESTICMIG2023', 'RDOMESTICMIG2024', 'RDOMESTICMIG2025',
       'RNETMIG2021', 'RNETMIG2022', 'RNETMIG2023', 'RNETMIG2024',
       'RNETMIG2025'],
      dtype='str')

In [14]:
usa_total = usa_population[
    usa_population["NAME"] == "United States"
]

usa_total[["NAME", "POPESTIMATE2025"]]

            NAME  POPESTIMATE2025
0  United States        341784857

In [15]:
usa_population_2025 = int(
    usa_total["POPESTIMATE2025"].iloc[0]
)

usa_population_summary = pd.DataFrame({
    "Population_group": ["Total population"],
    "Population": [usa_population_2025]
})

usa_population_summary

   Population_group  Population
0  Total population   341784857

In [21]:
usa_population_summary.to_csv(
    project_root / "reports" / "usa" / "tables" / "usa_population_summary.csv",
    index=False
)

In [22]:
usa_total[["NAME", "POPESTIMATE2025"]]

            NAME  POPESTIMATE2025
0  United States        341784857

In [23]:
usa_population_summary.to_csv(
    project_root / "reports" / "usa" / "tables" / "usa_population_summary.csv",
    index=False
)

In [24]:
usa_total[["NAME", "POPESTIMATE2025"]]

            NAME  POPESTIMATE2025
0  United States        341784857

In [25]:
usa_population_2025 = int(
    usa_total["POPESTIMATE2025"].iloc[0]
)

usa_population_summary = pd.DataFrame({
    "Population_group": ["Total population"],
    "Population": [usa_population_2025]
})

usa_population_summary

   Population_group  Population
0  Total population   341784857

In [26]:
usa_population_summary.to_csv(
    project_root / "reports" / "usa" / "tables" / "usa_population_summary.csv",
    index=False
)

In [27]:
age_file = project_root / "data" / "usa" / "population" / "us_age_population.csv"

print(age_file.exists())

True

In [29]:
usa_age = pd.read_csv(age_file)

usa_age.head()

,SEX,AGE,ESTIMATESBASE2020,POPESTIMATE2020,POPESTIMATE2021,POPESTIMATE2022,POPESTIMATE2023,POPESTIMATE2024,POPESTIMATE2025
0,0,0,3719470,3691723,3572165,3680529,3653453,3617221,3618898
1,0,1,3764281,3750601,3697247,3602579,3719819,3700305,3642657
2,0,2,3841150,3826776,3756935,3727216,3642279,3766783,3725891
3,0,3,3916585,3888055,3832978,3786311,3766965,3689270,3791993
4,0,4,3984785,3976772,3894042,3861295,3824021,3811156,3712428

In [30]:
usa_age.columns

Index(['SEX', 'AGE', 'ESTIMATESBASE2020', 'POPESTIMATE2020', 'POPESTIMATE2021',
       'POPESTIMATE2022', 'POPESTIMATE2023', 'POPESTIMATE2024',
       'POPESTIMATE2025'],
      dtype='str')

In [31]:
age_file = project_root / "data" / "usa" / "population" / "us_age_population.csv"

usa_age = pd.read_csv(age_file)

usa_age.head()

,SEX,AGE,ESTIMATESBASE2020,POPESTIMATE2020,POPESTIMATE2021,POPESTIMATE2022,POPESTIMATE2023,POPESTIMATE2024,POPESTIMATE2025
0,0,0,3719470,3691723,3572165,3680529,3653453,3617221,3618898
1,0,1,3764281,3750601,3697247,3602579,3719819,3700305,3642657
2,0,2,3841150,3826776,3756935,3727216,3642279,3766783,3725891
3,0,3,3916585,3888055,3832978,3786311,3766965,3689270,3791993
4,0,4,3984785,3976772,3894042,3861295,3824021,3811156,3712428

In [32]:
usa_age.columns

Index(['SEX', 'AGE', 'ESTIMATESBASE2020', 'POPESTIMATE2020', 'POPESTIMATE2021',
       'POPESTIMATE2022', 'POPESTIMATE2023', 'POPESTIMATE2024',
       'POPESTIMATE2025'],
      dtype='str')

In [33]:
usa_age_us = usa_age[
    usa_age["NAME"] == "United States"
]

KeyError: 'NAME'

In [34]:
usa_age.columns

Index(['SEX', 'AGE', 'ESTIMATESBASE2020', 'POPESTIMATE2020', 'POPESTIMATE2021',
       'POPESTIMATE2022', 'POPESTIMATE2023', 'POPESTIMATE2024',
       'POPESTIMATE2025'],
      dtype='str')

In [35]:
usa_age.head()

,SEX,AGE,ESTIMATESBASE2020,POPESTIMATE2020,POPESTIMATE2021,POPESTIMATE2022,POPESTIMATE2023,POPESTIMATE2024,POPESTIMATE2025
0,0,0,3719470,3691723,3572165,3680529,3653453,3617221,3618898
1,0,1,3764281,3750601,3697247,3602579,3719819,3700305,3642657
2,0,2,3841150,3826776,3756935,3727216,3642279,3766783,3725891
3,0,3,3916585,3888055,3832978,3786311,3766965,3689270,3791993
4,0,4,3984785,3976772,3894042,3861295,3824021,3811156,3712428

In [39]:
usa_age["SEX"].unique()

array([0, 1, 2])

In [42]:
usa_age_total = usa_age[
    usa_age["SEX"] == 0
]

usa_age_total.head()

,SEX,AGE,ESTIMATESBASE2020,POPESTIMATE2020,POPESTIMATE2021,POPESTIMATE2022,POPESTIMATE2023,POPESTIMATE2024,POPESTIMATE2025
0,0,0,3719470,3691723,3572165,3680529,3653453,3617221,3618898
1,0,1,3764281,3750601,3697247,3602579,3719819,3700305,3642657
2,0,2,3841150,3826776,3756935,3727216,3642279,3766783,3725891
3,0,3,3916585,3888055,3832978,3786311,3766965,3689270,3791993
4,0,4,3984785,3976772,3894042,3861295,3824021,3811156,3712428

In [43]:
usa_adults = usa_age_total[
    usa_age_total["AGE"] >= 18
]["POPESTIMATE2025"].sum()

usa_adults

np.int64(611548366)

In [44]:
usa_age.groupby("SEX").size()

SEX
0    102
1    102
2    102
dtype: int64

In [45]:
usa_age["AGE"].unique()[:20], usa_age["AGE"].max()

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19]),
 np.int64(999))

In [46]:
usa_age[
    (usa_age["SEX"] == 0) &
    (usa_age["AGE"] < 100)
]["POPESTIMATE2025"].sum()

np.int64(341665675)

In [47]:
usa_adults = usa_age[
    (usa_age["SEX"] == 0) &
    (usa_age["AGE"] >= 18) &
    (usa_age["AGE"] < 999)
]["POPESTIMATE2025"].sum()

usa_adults

np.int64(269763509)

In [48]:
usa_age_total = usa_age[
    (usa_age["SEX"] == 0) &
    (usa_age["AGE"] < 999)
]

usa_age_total["POPESTIMATE2025"].sum()

np.int64(341784857)

In [49]:
usa_adult_summary = pd.DataFrame({
    "Population_group": ["Adults 18+"],
    "Population": [usa_adults]
})

usa_adult_summary

  Population_group  Population
0       Adults 18+   269763509

In [50]:
usa_adult_summary.to_csv(
    project_root / "reports" / "usa" / "tables" / "usa_adult_population_summary.csv",
    index=False
)

In [51]:
obesity_file = (
    project_root
    / "data"
    / "usa"
    / "epidemiology"
    / "cdc_obesity_2024.csv"
)

usa_obesity = pd.read_csv(obesity_file)

usa_obesity.head()

        State Prevalence        95% CI
0     Alabama       38.9  (37.1, 40.7)
1      Alaska       34.0  (32.0, 36.0)
2     Arizona       33.3  (31.4, 35.3)
3    Arkansas       38.9  (37.2, 40.7)
4  California       29.1  (27.6, 30.5)

In [52]:
usa_obesity.columns

Index(['State', 'Prevalence', '95% CI'], dtype='str')

In [53]:
usa_obesity.head(10)

                  State Prevalence        95% CI
0               Alabama       38.9  (37.1, 40.7)
1                Alaska       34.0  (32.0, 36.0)
2               Arizona       33.3  (31.4, 35.3)
3              Arkansas       38.9  (37.2, 40.7)
4            California       29.1  (27.6, 30.5)
5              Colorado       25.0  (24.0, 26.0)
6           Connecticut       32.0  (30.4, 33.6)
7              Delaware       36.6  (34.5, 38.9)
8  District of Columbia       25.5  (23.5, 27.5)
9               Florida       29.6  (28.1, 31.3)

In [54]:
state_population = usa_population[
    (usa_population["SUMLEV"] == 40) &
    (usa_population["STATE"] != 72)  # Exclude Puerto Rico
][["NAME", "POPESTIMATE2025"]]

state_population.head()

          NAME  POPESTIMATE2025
14     Alabama          5193088
15      Alaska           737270
16     Arizona          7623818
17    Arkansas          3114791
18  California         39355309

In [55]:
usa_obesity = usa_obesity.rename(columns={"State": "NAME"})

usa_weighted = state_population.merge(
    usa_obesity,
    on="NAME",
    how="inner"
)

usa_weighted.head()

         NAME  POPESTIMATE2025 Prevalence        95% CI
0     Alabama          5193088       38.9  (37.1, 40.7)
1      Alaska           737270       34.0  (32.0, 36.0)
2     Arizona          7623818       33.3  (31.4, 35.3)
3    Arkansas          3114791       38.9  (37.2, 40.7)
4  California         39355309       29.1  (27.6, 30.5)

In [56]:
print("States matched:", len(usa_weighted))
print(usa_weighted.tail())

States matched: 51
             NAME  POPESTIMATE2025 Prevalence        95% CI
46       Virginia          8880107       32.3  (30.7, 34.0)
47     Washington          8001020       31.5  (30.7, 32.2)
48  West Virginia          1766147       41.4  (39.8, 43.0)
49      Wisconsin          5972787       37.4  (36.1, 38.7)
50        Wyoming           588753       32.5  (30.7, 34.3)

In [58]:
# Make sure the calculation columns are numeric
usa_weighted["POPESTIMATE2025"] = pd.to_numeric(
    usa_weighted["POPESTIMATE2025"],
    errors="coerce"
)

usa_weighted["Prevalence"] = pd.to_numeric(
    usa_weighted["Prevalence"],
    errors="coerce"
)

# Remove rows where either value is missing
usa_weighted = usa_weighted.dropna(
    subset=["POPESTIMATE2025", "Prevalence"]
)

# Calculate population-weighted obesity prevalence
usa_weighted["Weighted"] = (
    usa_weighted["POPESTIMATE2025"]
    * usa_weighted["Prevalence"]
)

usa_obesity_prevalence = (
    usa_weighted["Weighted"].sum()
    / usa_weighted["POPESTIMATE2025"].sum()
)

print(f"Weighted obesity prevalence: {usa_obesity_prevalence:.2f}%")

Weighted obesity prevalence: 33.06%

In [59]:
print("States used:", len(usa_weighted))
print(f"Weighted obesity prevalence: {usa_obesity_prevalence:.2f}%")

States used: 50
Weighted obesity prevalence: 33.06%

In [60]:
matched_names = set(usa_weighted["NAME"])

missing_states = state_population[
    ~state_population["NAME"].isin(matched_names)
]

missing_states

         NAME  POPESTIMATE2025
56  Tennessee          7315076

In [61]:
usa_obesity[
    ~usa_obesity["NAME"].isin(matched_names)
]

              NAME          Prevalence              95% CI
11            Guam                40.2        (32.9, 47.9)
40     Puerto Rico                36.2        (33.9, 38.4)
44       Tennessee  Insufficient data*  Insufficient data*
48  Virgin Islands                37.7        (30.7, 45.3)

In [62]:
usa_adults_with_obesity = (
    usa_adults * (usa_obesity_prevalence / 100)
)

print(f"Adults with obesity: {usa_adults_with_obesity:,.0f}")

Adults with obesity: 89,190,831

In [63]:
usa_epidemiology_summary = pd.DataFrame({
    "Measure": [
        "Adult population (18+)",
        "Population-weighted obesity prevalence",
        "Adults with obesity"
    ],
    "Value": [
        usa_adults,
        usa_obesity_prevalence,
        usa_adults_with_obesity
    ]
})

usa_epidemiology_summary

                                  Measure         Value
0                  Adult population (18+)  2.697635e+08
1  Population-weighted obesity prevalence  3.306260e+01
2                     Adults with obesity  8.919083e+07

In [65]:
usa_epidemiology_summary

                                  Measure         Value
0                  Adult population (18+)  2.697635e+08
1  Population-weighted obesity prevalence  3.306260e+01
2                     Adults with obesity  8.919083e+07

In [66]:
# USA Wegovy drug cost assumptions

usa_wegovy_monthly_cost = 1349.02
usa_months_per_year = 13

usa_wegovy_annual_cost = (
    usa_wegovy_monthly_cost * usa_months_per_year
)

print(f"Monthly Wegovy cost: ${usa_wegovy_monthly_cost:,.2f}")
print(f"Annual Wegovy cost: ${usa_wegovy_annual_cost:,.2f}")

Monthly Wegovy cost: $1,349.02
Annual Wegovy cost: $17,537.26

In [67]:
usa_cost_summary = pd.DataFrame({
    "Parameter": [
        "Wegovy monthly package cost",
        "Treatment cycles per year",
        "Annual drug cost per patient"
    ],
    "Value": [
        usa_wegovy_monthly_cost,
        usa_months_per_year,
        usa_wegovy_annual_cost
    ]
})

usa_cost_summary

                      Parameter     Value
0   Wegovy monthly package cost   1349.02
1     Treatment cycles per year     13.00
2  Annual drug cost per patient  17537.26

In [68]:
usa_cost_summary.to_csv(
    project_root
    / "reports"
    / "usa"
    / "tables"
    / "usa_drug_cost_summary.csv",
    index=False
)

In [69]:
usa_cost_summary

                      Parameter     Value
0   Wegovy monthly package cost   1349.02
1     Treatment cycles per year     13.00
2  Annual drug cost per patient  17537.26

In [70]:
# USA treatment uptake assumptions
# Same scenario assumptions used in the UK model

usa_uptake_year1 = 0.05
usa_uptake_year5 = 0.25

usa_uptake_summary = pd.DataFrame({
    "Year": [1, 5],
    "Treatment_uptake": [
        usa_uptake_year1,
        usa_uptake_year5
    ]
})

usa_uptake_summary

   Year  Treatment_uptake
0     1              0.05
1     5              0.25

In [71]:
usa_uptake_summary.to_csv(
    project_root
    / "reports"
    / "usa"
    / "tables"
    / "usa_treatment_uptake_summary.csv",
    index=False
)

In [72]:
usa_treated_year1 = (
    usa_adults_with_obesity
    * usa_uptake_year1
)

usa_treated_year5 = (
    usa_adults_with_obesity
    * usa_uptake_year5
)

print(f"Year 1 treated population: {usa_treated_year1:,.0f}")
print(f"Year 5 treated population: {usa_treated_year5:,.0f}")

Year 1 treated population: 4,459,542
Year 5 treated population: 22,297,708

In [73]:
usa_budget_year1 = (
    usa_treated_year1
    * usa_wegovy_annual_cost
)

usa_budget_year5 = (
    usa_treated_year5
    * usa_wegovy_annual_cost
)

print(f"Year 1 gross drug cost: ${usa_budget_year1:,.2f}")
print(f"Year 5 gross drug cost: ${usa_budget_year5:,.2f}")

Year 1 gross drug cost: $78,208,140,011.81
Year 5 gross drug cost: $391,040,700,059.03

In [74]:
usa_model_summary = pd.DataFrame({
    "Measure": [
        "Adult population (18+)",
        "Obesity prevalence",
        "Adults with obesity",
        "Annual drug cost per patient",
        "Treatment uptake Year 1",
        "Treatment uptake Year 5",
        "Treated population Year 1",
        "Treated population Year 5",
        "Gross drug cost Year 1",
        "Gross drug cost Year 5"
    ],
    "Value": [
        usa_adults,
        usa_obesity_prevalence,
        usa_adults_with_obesity,
        usa_wegovy_annual_cost,
        usa_uptake_year1,
        usa_uptake_year5,
        usa_treated_year1,
        usa_treated_year5,
        usa_budget_year1,
        usa_budget_year5
    ]
})

usa_model_summary

                        Measure         Value
0        Adult population (18+)  2.697635e+08
1            Obesity prevalence  3.306260e+01
2           Adults with obesity  8.919083e+07
3  Annual drug cost per patient  1.753726e+04
4       Treatment uptake Year 1  5.000000e-02
5       Treatment uptake Year 5  2.500000e-01
6     Treated population Year 1  4.459542e+06
7     Treated population Year 5  2.229771e+07
8        Gross drug cost Year 1  7.820814e+10
9        Gross drug cost Year 5  3.910407e+11

In [75]:
usa_model_summary.to_csv(
    project_root
    / "reports"
    / "usa"
    / "tables"
    / "usa_model_summary.csv",
    index=False
)

In [76]:
usa_model_summary

                        Measure         Value
0        Adult population (18+)  2.697635e+08
1            Obesity prevalence  3.306260e+01
2           Adults with obesity  8.919083e+07
3  Annual drug cost per patient  1.753726e+04
4       Treatment uptake Year 1  5.000000e-02
5       Treatment uptake Year 5  2.500000e-01
6     Treated population Year 1  4.459542e+06
7     Treated population Year 5  2.229771e+07
8        Gross drug cost Year 1  7.820814e+10
9        Gross drug cost Year 5  3.910407e+11